services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - fitness-network
    command:
      - air
      - -c
      - .air.toml
  webserver:
    build:
      context: .
    ports:
      - "5050:5050"
    networks:
      - fitness-network

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - fitness-network
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

networks:
  fitness-network:
    external: true